### ISSUE TITLE
TomeRater Review

### ISSUE THREAD

**Issue by franfranfranfran** [patran19/pwp-capstones#1]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 2
* _Comment(s):_ Included code runs without errors. It is a great idea to test all your methods and all the various cases, but the output when running the populate.py file is quite messy. It is hard to keep track of what is being tested and even when referencing the file itself, it takes a while to decipher that. Make use of comments and format your printed output if you want to have it all printed. Keeping your code and the output neat and readable goes a long way especially as your projects grow in size and complexity.
When trying to examine the slightly off output of the `most_positive_user` method, I noticed some errors that will crop up as you try to fix it. Capitalization matters, so [here](https://github.com/patran19/pwp-capstones/blob/master/PYTHON3/TomeRater_Project.py#L175-L177) User is not the same as user. Also, when defining a method, you give it a parameter `self`, this represents the object the method is called on and should NOT be used when calling the method. So here, there should be no inputs when calling this method. The same issue crops up in the other two analysis methods.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 2
* _Comment(s):_ Great job including all the required methods and classes. There are just a few key areas where improvements could be made. First, in diving into the printed output for the populate.py test, it seems like one of the books is not printing properly. Looks like it is the only object that is of the `book` class instead of one of the subclasses. When it comes to printing, what is the difference between `book` and the subclasses?
The output of the three analysis methods seems a bit off. Take a look at the criteria above for more info on this.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4
* _Comment(s):_ The relationships between classes and methods are clear and work well together.
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 3
* _Comment(s):_ Great work using various built-in Python features like `super()`, and the `values()` method in the `most_positive_user` function. There are a couple of things to keep in mind when using some of the other methods. First, the default for `for ... in ...` statements is to loop through a dictionaries keys. So no need to use the `keys()` method here. On [line 167](https://github.com/patran19/pwp-capstones/blob/master/PYTHON3/TomeRater_Project.py#L167) for instance, you could just do - `for book in self.books` - and it will work how you expect it to.
Similarly, check out [line 124](https://github.com/patran19/pwp-capstones/blob/master/PYTHON3/TomeRater_Project.py#L124-L125) for an opportunity to reduce redundant checks on email. Here you check if email is in the set of keys. Then directly inside the if you use the get method instead of just directly accessing the value at that key. You know there is a value at that key, because you've already checked for the existence of the key with the if statement.
Little changes like these go a long way to making your code clearer and more concise.
 
### Overall Score: 11/16
Great start on this project. With a few key tweaks, everything will be looking great. As a next step, try adjusting your three analysis methods to get rid of the extra `self` inputs and see if you can get accurate ouput.
Also, take a look around your program for opportunities to make your code easier to read and understand. Make use of well-placed line breaks to break up major content sections.
Have fun and keep up the good work!

**Comment by patran19** [comment]
Hi Francis,
Thank you for taking time to point out the good and bad of my first quite challenged Python code project.   It was truly a good jump start for me on this project.   I surely will try to get rid of the extra self inputs to get better accurate output.  Will also pay attention to well-placed line breaks to break up major content sections.
Thanks again,
/Paul
